### ISSUE TITLE
Improve the order list

### ISSUE THREAD

**Issue by zaiste** [saleor/storefront#1015]
- [ ] ~~Add order details page~~
- [x] Show status of payment
- [ ] [Allow to complete payments for not fully paid orders](https://github.com/saleor/storefront/issues/1031)

**Comment by mmiszy** [comment]
We've discussed it and decided not to implement the Order Details page at this time. It's generic and doesn't bring much value to our users; we'll spend this time on implementing something more interesting or difficult – i.e. vouchers, channels, geolocation etc.

**Comment by WholeWhales** [comment]
Storefront's order list is very important to users, why do you think it has no actual value?

**Comment by mmiszy** [comment]
@WholeWhales The order list has been successfully implemented, and the order details page, being closely analogous, contributes no educational value to our users.

It's important to emphasize that this repository serves as an example or starter kit and is not intended for direct use in its current form. Instead, you're encouraged to fork or clone and modify as per individual requirements.
