### ISSUE TITLE
Pass current channel in URL

### ISSUE THREAD

**Issue by mmiszy** [saleor/storefront#1029]
Channel should prefix all other product-related routes, i.e. `/default-channel/products` instead of just `/products`.

There are multiple channels to be fetched from the API, however, first step of this issue might be to hardcode the `default-channel`.

**Comment by santhoshm309** [comment]
Hey @mmiszy, I am new to OSS and would like to work on this issue. I am currently following the steps highlighted in our README.md file.

**Comment by mmiszy** [comment]
Great! Let us know if anything is unclear or you need any help.
