### ISSUE TITLE
Can't build the container image during `pnpm build`

### ISSUE THREAD

**Issue by matejak** [saleor/storefront#1050]
### Summary

When building from the Dockerfile, the build ends with following errors:

```
[3/4] STEP 12/12: RUN pnpm build

> saleor-storefront@0.1.0 prebuild /app
> pnpm run generate


> saleor-storefront@0.1.0 generate /app
> graphql-codegen --config .graphqlrc.ts

[STARTED] Parse Configuration
[SUCCESS] Parse Configuration
[STARTED] Generate outputs
[STARTED] Generate to src/gql/
[STARTED] Load GraphQL schemas
error: unknown option '--config'
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

I have no idea about what could possibly cause this, I am not too familiar with web development, and what puzzled me is that I couldn't even find any reference to `pnpm build`.

### Steps to reproduce

Checkout the storefront project, `main` branch, `57dfc2c52a76f010ff150060f2a73bbb32eb3d46` on 10th of Dec 2023.
Add `context: .` under `build` in the `docker-compose.yml`
Build the container image using docker-compose with correct build args.

**Comment by matejak** [comment]
@mmiszy Hello, it looks like that this is your level of expertise.

**Comment by jdmueller** [comment]
I am having this same issue. I have followed the directions: cloned the repo, cp .env.example to .env, I have run pnpm i. When I create a docker image of this repo it fails with the same image above. I saw also that the .env file was being ignored by the .gitignore file and even changing this does not fix it. It has been 3 years since I worked with a saleor store and I am not sure what I could be doing wrong since the directions seem simple enough to follow.

**Comment by jdmueller** [comment]
@matejak Were you ever able to resolve this?

**Comment by jdmueller** [comment]
<img width="1313" alt="Screenshot 2024-01-10 at 5 12 37 PM" src="https://github.com/saleor/storefront/assets/3661784/bf84b7f6-f704-4490-9d81-ab6c1a903468">

I have even specified these in the build variables section of the hub.docker system and the build still fails. I don't understand why the other 2 images will build correctly but this one does not.

**Comment by matejak** [comment]
Thank you for the pointer, I have set the build args incorrectly, and I got no complaints, however the build has failed in that weird way. With correct build arguments, it works :-)
I wouldn't say that the issue is fixed or invalid, as a small typo can lead one completely astray.

@jdmueller I guess that what you are after are build arguments, and not env variables. Env vars are overriden with build args in the Dockerfile. I am not familiar with the build system that you are using though.

**Comment by jdmueller** [comment]
@matejak I am using the hub.docker.com system that automatically generates an image file from my GitHub responistory whenever there is a push to the master. This builds a new image automatically and I can just restart the service and it automatically runs the new build. I have found this to work great for everything. And it works for the other 2 repos from saleor, but for some reason not this one. It even builds the image correctly without changing the .env file from .env.example. I just don't have enough experience with docker to understand what is going on or why it wouldn't even build the image. I haven't even tried to run it yet.

**Comment by jdmueller** [comment]
So I have created a new issue that specifies my problem since it sounds like the issue should be closed as you were able to figure out your problem. My issue is more specific to hub.docker.com.

**Comment by matejak** [comment]
Well, I close this as my issue is indeed resolved.
Anybody looking for the solution - pay attention to contents of your build arguments, make sure that they point to where the README says they should, and that those URLs are available from your build environment.
