### ISSUE TITLE
pnpm start indicates an error

### ISSUE THREAD

**Issue by RuoCJ** [saleor/storefront#1093]
### Summary

**I follow these steps**
![image](https://github.com/saleor/storefront/assets/53935240/bf080f1f-679d-4d31-ab45-a5e81b74ed28)
![image](https://github.com/saleor/storefront/assets/53935240/2a7ef400-2343-4eda-a695-a655cd25682a)

**But it keeps going wrong.**
```
pnpm start

> saleor-site@3.0.0-a.0 start /home/rain/code/saleor-storefront
> next dev -p 3000

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/rain/code/saleor-storefront/.env.development
info  - Loaded env from /home/rain/code/saleor-storefront/.env
info  - Using webpack 4. Reason: future.webpack5 option disabled https://nextjs.org/docs/messages/webpack5
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

        npm install --save-dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).

 ERROR  Command failed with exit code 1
```

### Steps to reproduce

1. pnpm start

### Output from envinfo

pnpm --version : pnpm@5
use ``npm install -g pnpm@5 `` install

**Comment by timuric** [comment]
Hey @RuoCJ I can't reproduce this issue, are you using the latest version from main?

**Comment by RuoCJ** [comment]
> Hey @RuoCJ I can't reproduce this issue, are you using the latest version from main?嘿，我无法重现这个问题，你使用的是main的最新版本吗?

Sorry, I have been busy recently, so I didn't have time to reply you. I have found the error, which is indeed a version problem
