### ISSUE TITLE
Issue with react-storefront docker compose config.

### ISSUE THREAD

**Issue by lukolszewski** [saleor/storefront#840]
### Summary

Trying to use react-storefront for the first time running in a docker container talking to saelor-platform (also in docker) results in a weird issue where products are not visible in the storefront. Very likely I'm doing something wrong as I'm just after a basic local setup and I'm trying defaults first.

Specifically I'm running saleor-platform in default configuration on a Linux host, then I cloned react-storefront repo. I updated docker-compose.yml to the attached. Then I run docker compose build, docker compose up, I connected storefront and checkout containers to the same network with docker connect so they can talk to the backend . This results in the storefront displaying a single word "Error" where product collections should be (screenshot attached). No errors are logged and grapql playground returns products and collections as expected. Additionally no products are visible in storefront at all.

The errors is coming from the following line: /apps/storefront/components/ProductCollection/ProductCollection.tsx Line 73.

Please advise.

![Screenshot from 2023-05-27 14-03-12](https://github.com/saleor/react-storefront/assets/43611481/569be8c2-f0b8-4e1d-a5fa-9fabd9f795d0)

[docker-compose-yml.txt](https://github.com/saleor/react-storefront/files/11581990/docker-compose-yml.txt)

### Steps to reproduce

Clone both saleor-platform and react-storefront. Update docker-compose.ymp in react-storefront to one attached.

Then run in both:
docker compose build
docker compose up

Then run:
docker network connect saleor-platform_saleor-backend-tier saleor-app-checkout
docker network connect saleor-platform_saleor-backend-tier storefront

Go to localhost:3000 and see no products displayed in the storefront.

## System:
 - OS: Linux 6.2 Arch Linux
 - CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
 - Memory: 15.45 GB / 31.26 GB
 - Container: Yes
 - Shell: 5.1.16 - /bin/bash
## Binaries:
 - Node: 19.9.0 - /usr/bin/node
 - npm: 8.19.2 - /usr/bin/npm
## Browsers:
 - Firefox: 112.0.1

[luk@archczop dev]$ docker exec -it storefront bash
root@c25fdbc7b945:/app# pnpm --version
7.11.0

**Comment by fedexin40** [comment]
I am just guessing, but I think the problem is that saleor core is rejecting connections from localhost:3000 due to the CORS , please check the logs from saleor core and see if you see something like connection refused

**Comment by Lodewic** [comment]
Hi, I am not the OP but I am reproducing the issue using Docker compose as well. Using the `canary` branch of `react-storefront`, and the `main` branch of `saleor-platform`.

In the storefront on port 3000 I see CORS errors in the browser console logs.

![image](https://github.com/saleor/react-storefront/assets/10435215/60da22a8-1560-49e4-9569-e083c0588a17)

I do not see any logs in the core api appearing about the storefront trying to make a call to the api at `http://api:8000/graphql/ `

---

I tried setting multiple environment variables for the backend api in the docker-compose.yml of saelor-platform:

- ALLOWED_HOST
  - localhost,api
  - localhost,api,storefront
  - "*"
- ALLOWED_CLIENT_HOSTS
  - localhost,storefront,api
  - "*"

But I'm not sure any of these have an effect, at least nothing worked for me.

Your initial guess seems to be correct  @fedexin40, but I am not sure what to do about it. What settings are available to allow cross-origin requests from the storefront? Should we change a setting in the backend or in the storefront?

**Comment by Lodewic** [comment]
I tried once more using all the same steps as @lukolszewski, except I used the original docker-compose build-args for `react-storefront`, using

`- SALEOR_API_URL=http://localhost:8000/graphql/ # handled by nginx` 

instead of 

`- SALEOR_API_URL=http://api:8000/graphql/ # handled by nginx`

And it works! I also thought we had to refer to the backend api host using `http://api:8000` instead of localhost... But I guess not.
