### ISSUE TITLE
Unable to confirm user email

### ISSUE THREAD

**Issue by fedexin40** [saleor/storefront#854]
### Summary

I am trying to create  a user with the option **_ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL_** enabled

From account/register page I fill in the values email and password. I also configured from the dashboard the user email plugin.

When clicking on the register button I am receiving an email confirmation, something like this 
`http://localhost:3000/account/confirm?email=federico.cruz.lozano%40gmail.com&token=bpcqx5-4f99c1be13d2d3eeee289775d13040a5 `

The problem is that when I try to open that link it only shows the home page and from the console, I can see this error
`Error: [@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "confirm" in Intl.NumberFormat. Using default locale: "en-US" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details
`
For me, this error makes sense since I cannot see a route directory to it, according to my knowledge the route would match with /[channel]/[locale], so the  **account** would be taken as the channel and **confirm** as the locale, the redirectURL is built from account/register.tsx

```javascript 
const handleRegister = handleSubmitForm(async (formData: RegisterFormData) => {
    const { data } = await register({
      variables: {
        input: {
          email: formData.email,
          password: formData.password,
          redirectUrl: `${window.location.origin}/account/confirm`,
          channel: currentChannel.slug,
        },
      },
    });
```

If I execute the confirmAccount mutation using the email address and token sent by email directly in http://localhost:8000/graphql/ the account is activated as expected, so I think the unique problem is the redirectURL page

Please advice about it, thank in advance

### Steps to reproduce

1.- Configure User email plugin in Saleor dashboard
2.- Create a new user account in Saleor storefront
3.- Receive my email the account confirmation email
4.- Open the URL received
5.- Nothing happens, there is an error in the console

`Error: [@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "confirm" in Intl.NumberFormat. Using default locale: "en-US" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details
`

## System:
 - OS: Linux 6.2 undefined
 - CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
 - Memory: 620.03 MB / 7.62 GB
 - Container: Yes
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
## Browsers:
 - Firefox: 112.0.2
## pnpm:
 - pnpm: 7.11.0
 ## react-storefront:
 - main branch
## Saleor core:
 - Release 3.13.17

**Comment by fedexin40** [comment]
@mmiszy kindly, any advice :)

**Comment by mmiszy** [comment]
You need to change that link to your confirmation page address.
