### ISSUE TITLE
Saleor Checkout App broken with latest 3.15 changes

### ISSUE THREAD

**Issue by SoniCoder** [saleor/storefront#881]
### Summary

While trying to add this app via manifest getting these errors:
Subscription query is not valid: Unknown type "TransactionActionRequest". Perhaps you meant "TransactionActionEnum", "TransactionAction", "TransactionCancelationRequested", "TransactionChargeRequested" or "TransactionRefundRequested"?
Error code INVALID on field webhooks
Look like we are no longer using TransactionActionRequest in newer versions, seems like saleor-app-checkout is still using it 

### Steps to reproduce

1. Use 3.15 API
2. Use latest checkout app on canary branch

**Comment by SoniCoder** [comment]
The following change seems to be the cause:

- Remove input and fields related to transaction API and deprecated in 3.13 - #13020 by @korycins
  - `WebhookEventTypeEnum.TRANSACTION_ACTION_REQUEST` - Use `TRANSACTION_CHARGE_REQUESTED`, `TRANSACTION_REFUND_REQUESTED`, `TRANSACTION_CANCELATION_REQUESTED` instead.
  - `WebhookEventTypeAsyncEnum.TRANSACTION_ACTION_REQUEST` - Use `TRANSACTION_CHARGE_REQUESTED`, `TRANSACTION_REFUND_REQUESTED`, `TRANSACTION_CANCELATION_REQUESTED` instead.
  - `WebhookSampleEventTypeEnum.TRANSACTION_ACTION_REQUEST`
  - `TransactionItem`:
    - `voidedAmount` - Use `canceledAmount` instead.
    - `status` - The amounts can be used to define the current status of transactions.
    - `type` - Use `name` or `message`.
    - `reference` - Use `pspReference` instead.
  - `TransactionActionEnum.VOID` - Use `CANCEL` instead.
  - `OrderEvent.status` - Use `TransactionEvent` to track the status of `TransactionItem`.
  - `OrderEventsEnum`:
    - `TRANSACTION_CAPTURE_REQUESTED` - Use `TRANSACTION_CHARGE_REQUESTED` instead.
    - `TRANSACTION_VOID_REQUESTED` - Use `TRANSACTION_CANCEL_REQUESTED` instead.
  - `TransactionStatus`
  - `TransactionEvent`:
    - `status` - Use `type` instead.
    - `reference` - Use `pspReference` instead.
    - `name` - Use `message` instead.
  - `TransactionCreateInput`:
    - `status` - The amounts can be used to define the current status of transactions.
    - `type` - Use `name` or `message`.
    - `reference` - Use `pspReference` instead.
    - `voidedAmount` - Use `canceledAmount` instead.
  - `TransactionEventInput`:
    - `status` - Status will be calculated by Saleor.
    - `reference` - Use `pspReference` instead.
    - `name` - Use `message` instead.
  - `TransactionUpdateInput`:
    - `status` - The amounts can be used to define the current status of transactions.
    - `type` - Use `name` or `message`.
    - `reference` - Use `pspReference` instead.
    - `voidedAmount` - Use `canceledAmount` instead.
  - `TransactionActionRequest` - Use `TransactionChargeRequested`, `TransactionRefundRequested`, `TransactionCancelationRequested` instead.

**Comment by PaulCardoos** [comment]
hi team, 

i have made changes in this code base to reflect the deprecation's above and below is the new payload that the saleor-app-checkout `api/manifest` endpoint produces. I am still receiving `INVALID_MANIFEST_FORMAT`, can any one tell me what is invalid about this payload or point me to docs when I see what the expected payload is to install apps for version 3.15 of the dashboard?

```
{
    "id": "saleor.checkout.app",
    "version": "0.0.0",
    "name": "Checkout",
    "about": "Saleor checkout app to quickly configure and customize checkout in your store.",
    "permissions": [
        "HANDLE_PAYMENTS",
        "HANDLE_CHECKOUTS",
        "MANAGE_ORDERS",
        "MANAGE_CHECKOUTS"
    ],
    "appUrl": "https://4b02-2601-196-4a80-4ba0-778-6659-3a3b-90d.ngrok-free.app",
    "dataPrivacyUrl": "https://4b02-2601-196-4a80-4ba0-778-6659-3a3b-90d.ngrok-free.app/data-privacy",
    "supportUrl": "https://4b02-2601-196-4a80-4ba0-778-6659-3a3b-90d.ngrok-free.app/support",
    "tokenTargetUrl": "https://4b02-2601-196-4a80-4ba0-778-6659-3a3b-90d.ngrok-free.app/api/register",
    "webhooks": [
        {
            "query": "subscription TransactionActionRequestSubscription { event { ... on TransactionChargeRequested { transaction { id reference type authorizedAmount { amount currency } chargedAmount { amount } canceledAmount { amount } refundedAmount { amount } } action { actionType amount } } }}",
            "name": "Checkout app payment notifications",
            "targetUrl": "https://4b02-2601-196-4a80-4ba0-778-6659-3a3b-90d.ngrok-free.app/api/webhooks/saleor/transaction-action-request",
            "isActive": true,
            "asyncEvents": [
                "TRANSACTION_CHARGE_REQUESTED"
            ]
        }
    ]
}
```
