### ISSUE TITLE
saleor-app-checkout throwing Error code INVALID_MANIFEST_FORMAT on field manifestUrl

### ISSUE THREAD

**Issue by PaulCardoos** [saleor/storefront#884]
hello. 

 i have ran `pnpm run generate` to update graphql schema and dealth with the 3.15 saleor api deprecations in in the saleor-checkout-app, yet when i go to install the app on saleor dashboard cloud version 3.15 I am given this error.

![Screenshot from 2023-09-18 14-33-53](https://github.com/saleor/storefront/assets/77507230/6d49b7a1-5fdf-46d6-ab24-d1d004298e52)

this is the format of the manifest

```json
{
    "id": "saleor.checkout.app",
    "version": "0.0.0",
    "name": "Checkout",
    "about": "Saleor checkout app to quickly configure and customize checkout in your store.",
    "permissions": [
        "HANDLE_PAYMENTS",
        "HANDLE_CHECKOUTS",
        "MANAGE_ORDERS",
        "MANAGE_CHECKOUTS"
    ],
    "appUrl": "https://a774-2601-196-4a80-4ba0-de6-939f-a188-543d.ngrok-free.app",
    "dataPrivacyUrl": "https://a774-2601-196-4a80-4ba0-de6-939f-a188-543d.ngrok-free.app/data-privacy",
    "supportUrl": "https://a774-2601-196-4a80-4ba0-de6-939f-a188-543d.ngrok-free.app/support",
    "tokenTargetUrl": "https://a774-2601-196-4a80-4ba0-de6-939f-a188-543d.ngrok-free.app/api/register",
    "webhooks": [
        {
            "query": "subscription TransactionActionRequestSubscription { event { ... on TransactionChargeRequested { transaction { id pspReference name authorizedAmount { amount currency } chargedAmount { amount } canceledAmount { amount } refundedAmount { amount } } action { actionType amount } } }}",
            "name": "Checkout app payment notifications",
            "targetUrl": "https://a774-2601-196-4a80-4ba0-de6-939f-a188-543d.ngrok-free.app/api/webhooks/saleor/transaction-action-request",
            "isActive": true,
            "asyncEvents": [
                "TRANSACTION_CHARGE_REQUESTED"
            ]
        }
    ]
}
```

can anyone identify this issue or has seen a similar issuue? appreciate any help

**Comment by SoniCoder** [comment]
@PaulCardoos Can you please tell me how was this closed? What's the fix?

**Comment by PaulCardoos** [comment]
Hi

**Comment by PaulCardoos** [comment]
Hello, initially i was having the same error as https://github.com/saleor/storefront/issues/881 but then i ran `pnpm run generate` to upgrade graphql schema and updated the code according. Then I received the error above and it was being cause because TRANSACTION_CHARGE_REQUESTED is not a valid AsyncWebhookEventType. So, I tried any other valids option.

`type AsyncWebhookEventType = "ADDRESS_CREATED" | "ADDRESS_UPDATED" | "ADDRESS_DELETED" | "APP_INSTALLED" | "APP_UPDATED" | "APP_DELETED" | "APP_STATUS_CHANGED" | "ATTRIBUTE_CREATED" | "ATTRIBUTE_UPDATED" | "ATTRIBUTE_DELETED" | "ATTRIBUTE_VALUE_CREATED" | "ATTRIBUTE_VALUE_UPDATED" | "ATTRIBUTE_VALUE_DELETED" | "CATEGORY_CREATED" | "CATEGORY_UPDATED" | "CATEGORY_DELETED" | "CHANNEL_CREATED" | "CHANNEL_UPDATED" | "CHANNEL_DELETED" | "CHANNEL_STATUS_CHANGED" | "GIFT_CARD_CREATED" | "GIFT_CARD_UPDATED" | "GIFT_CARD_DELETED" | "GIFT_CARD_STATUS_CHANGED" | "GIFT_CARD_METADATA_UPDATED" | "MENU_CREATED" | "MENU_UPDATED" | "MENU_DELETED" | "MENU_ITEM_CREATED" | "MENU_ITEM_UPDATED" | "MENU_ITEM_DELETED" | "ORDER_CREATED" | "ORDER_CONFIRMED" | "ORDER_FULLY_PAID" | "ORDER_UPDATED" | "ORDER_CANCELLED" | "ORDER_FULFILLED" | "ORDER_METADATA_UPDATED" | "FULFILLMENT_CREATED" | "FULFILLMENT_CANCELED" | "FULFILLMENT_APPROVED" | "FULFILLMENT_METADATA_UPDATED" | "DRAFT_ORDER_CREATED" | "DRAFT_ORDER_UPDATED" | "DRAFT_ORDER_DELETED" | "SALE_CREATED" | "SALE_UPDATED" | "SALE_DELETED" | "SALE_TOGGLE" | "INVOICE_REQUESTED" | "INVOICE_DELETED" | "INVOICE_SENT" | "CUSTOMER_CREATED" | "CUSTOMER_UPDATED" | "CUSTOMER_DELETED" | "CUSTOMER_METADATA_UPDATED" | "COLLECTION_CREATED" | "COLLECTION_UPDATED" | "COLLECTION_DELETED" | "COLLECTION_METADATA_UPDATED" | "PRODUCT_CREATED" | "PRODUCT_UPDATED" | "PRODUCT_DELETED" | "PRODUCT_METADATA_UPDATED" | "PRODUCT_MEDIA_CREATED" | "PRODUCT_MEDIA_UPDATED" | "PRODUCT_MEDIA_DELETED" | "PRODUCT_VARIANT_CREATED" | "PRODUCT_VARIANT_UPDATED" | "PRODUCT_VARIANT_DELETED" | "PRODUCT_VARIANT_METADATA_UPDATED" | "PRODUCT_VARIANT_OUT_OF_STOCK" | "PRODUCT_VARIANT_BACK_IN_STOCK" | "PRODUCT_VARIANT_STOCK_UPDATED" | "CHECKOUT_CREATED" | "CHECKOUT_UPDATED" | "CHECKOUT_METADATA_UPDATED" | "NOTIFY_USER" | "PAGE_CREATED" | "PAGE_UPDATED" | "PAGE_DELETED" | "PAGE_TYPE_CREATED" | "PAGE_TYPE_UPDATED" | "PAGE_TYPE_DELETED" | "PERMISSION_GROUP_CREATED" | "PERMISSION_GROUP_UPDATED" | "PERMISSION_GROUP_DELETED" | "SHIPPING_PRICE_CREATED" | "SHIPPING_PRICE_UPDATED" | "SHIPPING_PRICE_DELETED" | "SHIPPING_ZONE_CREATED" | "SHIPPING_ZONE_UPDATED" | "SHIPPING_ZONE_DELETED" | "SHIPPING_ZONE_METADATA_UPDATED" | "STAFF_CREATED" | "STAFF_UPDATED" | "STAFF_DELETED" | "TRANSACTION_ACTION_REQUEST" | "TRANSACTION_ITEM_METADATA_UPDATED" | "TRANSLATION_CREATED" | "TRANSLATION_UPDATED" | "WAREHOUSE_CREATED" | "WAREHOUSE_UPDATED" | "WAREHOUSE_DELETED" | "WAREHOUSE_METADATA_UPDATED" | "VOUCHER_CREATED" | "VOUCHER_UPDATED" | "VOUCHER_DELETED"  | "VOUCHER_METADATA_UPDATED" | "OBSERVABILITY" | "THUMBNAIL_CREATED";`

and it successfully install

**Comment by PaulCardoos** [comment]
i actually am unsure about which option to use for AsyncWebhookEventType

**Comment by PaulCardoos** [comment]
i dont mind posting a PR for this but i am unable to verify if anyone else is receiving the same issue

**Comment by SoniCoder** [comment]
I my case, pnpm run generate is throwing the following error:

node@4c025003bd59:/app/apps/saleor-app-checkout$ pnpm run generate              
> saleor-app-checkout@0.0.0 generate /app/apps/saleor-app-checkout              
> DOTENV_CONFIG_PATH=.env graphql-codegen -r env-vars --config codegen.yml      
Cannot read properties of undefined (reading 'split')                       
 ELIFECYCLE  Command failed with exit code 1.

**Comment by PaulCardoos** [comment]
hm, i dont know, it depends on your environment. Ive dockerized my dev and prod environment so i dont have to deal with dependencies as often. I would try running the command from the root of the repository, in my case its  `react-storefront` but it just changed today to `storefront`. If that doesnt work then i would try `pnpm install` and then try again
