### ISSUE TITLE
Add Stripe to Storefront

### ISSUE THREAD

**Issue by mmiszy** [saleor/storefront#900]

**Comment by matteius** [comment]
What is the state of this in relation to the saleor stripe app?  https://apps.saleor.io/apps/stripe

I was trying to get the stripe app installed locally today in latest dashboard, but I get errors from backend despite using a staff/superuser account: `saleor.core.exceptions.PermissionDenied: To access this path, you need one of the following permissions: AUTHENTICATED_STAFF_USER, AUTHENTICATED_APP`.

I am wondering if I were to get saleor stripe app installed correctly, would the new storefront show the payment method or is that what this ticket is about?

**Comment by mmiszy** [comment]
This ticket is about adding a frontend component for the Saleor Stripe App.

**Comment by matteius** [comment]
Ok awesome -- I just figured out getting the Stripe app installed, so I see the payment gateway in the response; I suppose I am just waiting on this ticket now 👍
