### ISSUE TITLE
As a user I can't remove items from the shopping cart

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/storefront#901]
### Summary

When I add items to the shopping cart it is impossible to remove it. 
![image](https://github.com/saleor/storefront/assets/25908728/f2114fd1-de94-441a-8239-1ea8b5e22543)

### Steps to reproduce

1. Add few items to the basket
2. Go into shopping cart

Current result: It is impossible to remove any items

**Comment by kumarvivekpandey** [comment]
Hi Team,

I hope you're doing well. I noticed the issue #[901] titled "[As a user I can't remove items from the shopping cart]" in your repository, and I'd like to contribute by fixing it. I believe I've identified the problem and have a potential solution in mind.

Here's my plan for addressing this issue:

1. **Understanding the Issue:** I'll start by thoroughly understanding the problem described in the issue and examining the codebase related to it.

2. **Proposed Solution:** Based on my analysis, I'll propose a solution that should address the issue. This may involve making code changes, writing tests, or updating documentation as needed.

3. **Pull Request:** Once I'm confident in my solution, I'll fork the repository, create a new branch, and make the necessary changes. Then, I'll submit a pull request to your repository, referencing this issue.

4. **Testing:** I'll ensure that my changes do not introduce new issues and will test the fix against different scenarios or edge cases, if applicable.

5. **Documentation:** If necessary, I'll update the documentation to reflect the changes I've made.

6. **Continuous Communication:** I'll keep you updated on the progress of the pull request and address any feedback or changes you may suggest promptly.

Please let me know if you have any specific guidelines or coding conventions I should follow while working on this issue. If there are any additional details or context you'd like to provide, I'd greatly appreciate it.

Thank you for maintaining this valuable open-source project, and I look forward to contributing to its improvement.

Best regards,
vivek
