### ISSUE TITLE
UI fix for 'your cart is empty' view

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/storefront#902]
### Summary

The info about empty cart is not aligned, the same with the button 'go back to store'. I suggest to use all space available on the page instead of splitting page. Or centre the info to the left 
![image](https://github.com/saleor/storefront/assets/25908728/cf6144aa-8461-4fcc-bee1-cdd6486f890d)

### Steps to reproduce

1. Add 3 items to the basket 
2. Go to checkout 
3. In checkout set quantity to 0 for all items 
Result:
![Screenshot 2023-10-06 at 12 47 25](https://github.com/saleor/storefront/assets/25908728/cc8dfd6b-8a60-41cb-a752-f2546dce9dad)

The info about empty cart is not aligned, the same with the button 'go back to store'.

**Comment by kumarvivekpandey** [comment]
Hi [Owner/Maintainer's Name],

I hope you're doing well. I noticed the issue #[902] titled "[UI fix for 'your cart is empty' view]" in your repository, and I'd like to contribute by fixing it. I believe I've identified the problem and have a potential solution in mind.

Here's my plan for addressing this issue:

1. **Understanding the Issue:** I'll start by thoroughly understanding the problem described in the issue and examining the codebase related to it.

2. **Proposed Solution:** Based on my analysis, I'll propose a solution that should address the issue. This may involve making code changes, writing tests, or updating documentation as needed.

3. **Pull Request:** Once I'm confident in my solution, I'll fork the repository, create a new branch, and make the necessary changes. Then, I'll submit a pull request to your repository, referencing this issue.

4. **Testing:** I'll ensure that my changes do not introduce new issues and will test the fix against different scenarios or edge cases, if applicable.

5. **Documentation:** If necessary, I'll update the documentation to reflect the changes I've made.

6. **Continuous Communication:** I'll keep you updated on the progress of the pull request and address any feedback or changes you may suggest promptly.

Please let me know if you have any specific guidelines or coding conventions I should follow while working on this issue. If there are any additional details or context you'd like to provide, I'd greatly appreciate it.

Thank you for maintaining this valuable open-source project, and I look forward to contributing to its improvement.

Best regards,
Vivek

**Comment by kumarvivekpandey** [comment]
@mmiszy  hey assign this to me
