### ISSUE TITLE
Amount of items in the basket is not calculating properly

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/storefront#905]
### Summary

Amount of items in the basket is not calculating properly if I add the same item with the same size. It is counted as 1, but price is correct.

### Steps to reproduce

1. Add to the cart 1 t-shirt size L
2. Add 2 t-shirts size M
3. Add 1 t-shirt XL size 
Result:
In the basket there will be visible only 3 items, should be counted as 4. 
![image](https://github.com/saleor/storefront/assets/25908728/28f55131-0d61-4977-8ff3-1b80a1f0371a)

**Comment by timuric** [comment]
Fixed in https://github.com/saleor/storefront/pull/921

**Comment by timuric** [comment]
Fixed in https://github.com/saleor/storefront/pull/922
