### ISSUE TITLE
Add to bag doesn't work for products without variants

### ISSUE THREAD

**Issue by timuric** [saleor/storefront#932]
### Summary

Add to cart doesn't produce any effect

### Steps to reproduce

Try adding item to cart
https://storefront-saleor-example.vercel.app/products/saleor-sunglasses?variant=UHJvZHVjdFZhcmlhbnQ6MzMw

**Comment by grzegorzpokorski** [comment]
Hi @timuric I found the reason why it does not work. It does not work because this particular product are unavailable 🙂 If you will I can provide solution later for that.

**Comment by mmiszy** [comment]
Fixed
