### ISSUE TITLE
The password eye icon is not aligned

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/storefront#962]
1. Start typing password
2. Change the focus
Result: The eye icon is not aligned into the frame
<img width="816" alt="image" src="https://github.com/saleor/storefront/assets/25908728/fe572326-2313-42a9-b794-9c5fc5e8aa33">

**Comment by KriteshTimsina** [comment]
Can i work on this?

**Comment by zaiste** [comment]
@KriteshTimsina sure

**Comment by KriteshTimsina** [comment]
I've resolved the issue but having some issue pushing code.
error: 'saleor-storefront-0-0/' does not have a commit checked out
fatal: adding files failed
can you help me out? @zaiste

**Comment by mmiszy** [comment]
Fixed in https://github.com/saleor/storefront/pull/977
