### ISSUE TITLE
Fix padding

### ISSUE THREAD

**Issue by timuric** [saleor/storefront#976]
### Summary

Fix padding and remove bottom line 

<img width="670" alt="image" src="https://github.com/saleor/storefront/assets/4006792/b53a8c10-54a5-4060-8868-f399dfe56d91">

### Steps to reproduce

1. Go to checkout
2. Sing in

**Comment by AnnaKondrDeveloper** [comment]
@timuric Hello! I can do it! Could you assign this to me, please?
