### ISSUE TITLE
SEO optimization, add OG images and page titles

### ISSUE THREAD

**Issue by timuric** [saleor/storefront#980]
[] Product page should include product image and product SEO fields
`<title>{product.name} | {product.seoTitle}</title>`
`<meta name="description" content={product.seoDescription}/>`

[] Use description of Collections and categories
`<title>{collection.name} | {collection.seoTitle}</title>`
`<meta name="description" content={collection.seoDescription}/>`

[] Pages like account and Checkout should use [Name of the page] [Global title of the store]
`<title>Checkout | ACME store</title>`

**Comment by samiralibabic** [comment]
Hi 👋
I would like to work on this. When you say "product SEO fields" do you mean keywords or anything in backend?

**Comment by samiralibabic** [comment]
Seems proper to me. @timuric can you provide some more info?

**Comment by timuric** [comment]
Hey @samiralibabic I have updated description, let me know if you need more details
